// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Chipbreaker Contributors

//! The outward normal of a tool's surface, analytically.
//!
//! # The second half of a sentence written at Unit 9
//!
//! Unit 9 said the surface normal is free at both sites where a span endpoint is
//! born: the triangle normal during construction, and **the analytic tool
//! surface normal during a cut**. Only the first was implemented. Every cut face
//! in the engine carried the placeholder, which decodes to `+Z`, negated by the
//! subtraction into `(0, 0, -1)` — so a slot's two walls, facing opposite
//! directions, shared one normal.
//!
//! Nothing caught it for five units, and the reasons are structural rather than
//! careless:
//!
//! - Dual contouring averages several crossings per vertex, so one bad plane is
//!   absorbed rather than seen.
//! - Unit 9's sharp-feature measurements used **uncut** boxes, where every
//!   normal comes from construction and is correct.
//! - Unit 12's deviation field is the first consumer to use a single normal
//!   alone, with nothing to average against.
//!
//! # One rotation, not four cases
//!
//! A tool is a solid of revolution about its own `+Z`, generated by a profile in
//! the half-plane `(r, z)`. The obvious approach is to write each revolved
//! surface as an implicit `F(r, z) = 0` and take `grad F`: cylinder, cone,
//! annular disc, sphere, torus. That is five gradients, five sign conventions,
//! and a degenerate case where a cone's slope runs to infinity.
//!
//! There is a shorter route. A profile runs from the tip upward with the solid
//! on its left, so the outward direction is the tangent turned **ninety degrees
//! clockwise**, which in the `(r, z)` plane is
//!
//! ```text
//! (t_r, t_z)  ->  (t_z, -t_r)
//! ```
//!
//! and that single rotation covers every element:
//!
//! | element                    | tangent   | outward   | surface        |
//! |----------------------------|-----------|-----------|----------------|
//! | tip disc, `(0,0)->(r,0)`   | `(+, 0)`  | `(0, -)`  | annular, faces down |
//! | flank, `(r,0)->(r,L)`      | `(0, +)`  | `(+, 0)`  | cylinder       |
//! | taper                      | `(+, +)`  | `(+, -)`  | cone           |
//! | shoulder, `(R,L)->(r,L)`   | `(-, 0)`  | `(0, +)`  | annular, faces up |
//!
//! For an arc the rotation has a closed form: rotating the counter-clockwise
//! tangent `(-sin t, cos t)` by minus ninety degrees gives `(cos t, sin t)`,
//! which is the radius vector itself. So an arc's outward profile normal is
//! `direction.sign()` times the vector from its centre — **the sphere and the
//! torus are the same formula**, and their difference (centre on the axis or
//! off it) never appears here at all. It appears in the raycaster, where the
//! quadratic and quartic branches genuinely differ, but not in the normal.
//!
//! Lifting to three dimensions is then one step. The profile normal `(n_r, n_z)`
//! spreads its radial part over `x` and `y` in proportion to where the point
//! sits around the axis:
//!
//! ```text
//! (x, y, z)  ->  ( n_r * x/rho,  n_r * y/rho,  n_z )
//! ```
//!
//! # Sign
//!
//! **Outward from the tool solid.** The subtraction in [`crate::spans`] negates
//! it, because a face cut by the tool bounds the *workpiece*, whose material
//! lies on the side the cutter's does not. That negation is where the convention
//! is enforced; this module's only job is to point away from the cutter.

use crate::math::{Vec2, Vec3};
use crate::transcendental as t;

use super::{ArcDirection, Profile, ProfileElement};

/// Points closer than this to the axis are treated as being on it.
const NEAR_AXIS: f64 = 1.0e-12;

/// Outward normal of the tool surface at `p`, in the tool's own frame.
///
/// `p` is in tool coordinates: the axis is `+Z`, the tip at the origin. Every
/// three-axis sweep places the tool by translation alone, so this is also the
/// world normal — the reason [`crate::sweep`] can store what the raycaster
/// returns without transforming it.
///
/// Returns `None` only for a profile with no surface at all, which
/// [`Profile::new`] rejects.
#[must_use]
pub fn surface_normal(profile: &Profile, p: Vec3) -> Option<Vec3> {
    let rho = t::hypot(p.x, p.y);
    let here = Vec2::new(rho, p.z);

    // The element whose surface the point is nearest to. Nearest rather than
    // first-containing: a span endpoint can land exactly on the seam between two
    // elements, where either answer is defensible, and "nearest" is the only
    // rule that does not depend on the order they were declared in.
    let mut best: Option<(f64, Vec2)> = None;
    let mut consider = |distance: f64, normal: Vec2| {
        if best.is_none_or(|(d, _)| distance < d) {
            best = Some((distance, normal));
        }
    };

    for roled in profile.elements() {
        let (distance, normal) = element_normal(&roled.element, here);
        consider(distance, normal);
    }

    // The top cap, which closes the solid and is not an element. It faces `+Z`:
    // the profile ends there and the disc back to the axis is the lid.
    let top = profile.top();
    if rho <= top.x {
        consider((here.y - top.y).abs(), Vec2::new(0.0, 1.0));
    }

    let (_, profile_normal) = best?;
    Some(lift(profile_normal, p, rho))
}

/// Spreads a profile-plane normal around the axis.
fn lift(n: Vec2, p: Vec3, rho: f64) -> Vec3 {
    if rho <= NEAR_AXIS {
        // On the axis the radial direction is undefined, and a surface that
        // reaches the axis is either the tip point or a cap; both are axial.
        return Vec3::new(0.0, 0.0, if n.y >= 0.0 { 1.0 } else { -1.0 });
    }
    let lifted = Vec3::new(n.x * p.x / rho, n.x * p.y / rho, n.y);
    lifted.normalize().unwrap_or(Vec3::new(0.0, 0.0, 1.0))
}

/// Distance from `here` to this element in the profile plane, and the outward
/// normal of the element at the nearest point.
fn element_normal(element: &ProfileElement, here: Vec2) -> (f64, Vec2) {
    match *element {
        ProfileElement::Segment { start, end } => segment_normal(start, end, here),
        ProfileElement::Arc {
            center, direction, ..
        } => arc_normal(element, center, direction, here),
    }
}

/// A segment: cylinder, cone, or annular disc, all one rotation.
fn segment_normal(start: Vec2, end: Vec2, here: Vec2) -> (f64, Vec2) {
    let tangent = end - start;
    let length_sq = tangent.x * tangent.x + tangent.y * tangent.y;
    // The outward normal is constant along a segment, so it is computed once and
    // the projection only decides *how far away* the point is.
    let outward = Vec2::new(tangent.y, -tangent.x)
        .normalize()
        .unwrap_or(Vec2::new(1.0, 0.0));
    if length_sq <= 0.0 {
        return ((here - start).length(), outward);
    }
    let offset = here - start;
    let u = ((offset.x * tangent.x + offset.y * tangent.y) / length_sq).clamp(0.0, 1.0);
    let nearest = start + tangent * u;
    ((here - nearest).length(), outward)
}

/// An arc: sphere when its centre is on the axis, torus when it is not, and the
/// same formula either way.
fn arc_normal(
    element: &ProfileElement,
    center: Vec2,
    direction: ArcDirection,
    here: Vec2,
) -> (f64, Vec2) {
    let radius = element.radius().unwrap_or(0.0);
    let offset = here - center;
    let Some(radial) = offset.normalize() else {
        // Dead centre: every direction is equally outward, so answer with the
        // start point's and let a nearer element win, which one always will.
        let start = element.start();
        let fallback = (start - center).normalize().unwrap_or(Vec2::new(1.0, 0.0));
        return (radius, fallback * direction.sign());
    };
    let outward = radial * direction.sign();

    let angle = t::atan2(offset.y, offset.x);
    let distance = if element.contains_angle(angle, 0.0) {
        (offset.length() - radius).abs()
    } else {
        // Past the end of the sweep, the nearest point of the arc is an
        // endpoint. Using the circle's distance there would claim a surface that
        // is not present and can beat the element that really is.
        (here - element.start())
            .length()
            .min((here - element.end()).length())
    };
    (distance, outward)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tool::catalog::{Shank, ball_end_mill, bull_end_mill, flat_end_mill};

    fn close(a: Vec3, b: Vec3) -> bool {
        (a.x - b.x).abs() < 1.0e-9 && (a.y - b.y).abs() < 1.0e-9 && (a.z - b.z).abs() < 1.0e-9
    }

    #[test]
    fn a_flank_points_radially_outward_at_every_bearing() {
        // The defect in one assertion: two flanks facing opposite ways must not
        // share a normal.
        let p = flat_end_mill(6.0, 20.0, &Shank::plain(6.0, 40.0)).expect("valid");
        for (x, y, want) in [
            (3.0, 0.0, Vec3::new(1.0, 0.0, 0.0)),
            (-3.0, 0.0, Vec3::new(-1.0, 0.0, 0.0)),
            (0.0, 3.0, Vec3::new(0.0, 1.0, 0.0)),
            (0.0, -3.0, Vec3::new(0.0, -1.0, 0.0)),
        ] {
            let n = surface_normal(&p, Vec3::new(x, y, 5.0)).expect("has a surface");
            assert!(
                close(n, want),
                "at ({x}, {y}, 5) expected {want:?}, got {n:?}"
            );
        }
    }

    #[test]
    fn a_flat_tip_faces_down_and_the_top_cap_faces_up() {
        let p = flat_end_mill(6.0, 20.0, &Shank::plain(6.0, 40.0)).expect("valid");
        let tip = surface_normal(&p, Vec3::new(1.5, 0.0, 0.0)).expect("has a surface");
        assert!(tip.z < -0.999, "the tip disc faces -Z, got {tip:?}");
        let top = p.top();
        let cap = surface_normal(&p, Vec3::new(0.5, 0.0, top.y)).expect("has a surface");
        assert!(cap.z > 0.999, "the top cap faces +Z, got {cap:?}");
    }

    #[test]
    fn a_ball_nose_points_away_from_its_centre() {
        let p = ball_end_mill(6.0, 20.0, &Shank::plain(6.0, 40.0)).expect("valid");
        let bottom = surface_normal(&p, Vec3::new(0.0, 0.0, 0.0)).expect("has a surface");
        assert!(
            bottom.z < -0.999,
            "the lowest point faces -Z, got {bottom:?}"
        );

        // Forty-five degrees round the ball: radius 3, centre on the axis at 3.
        let s = 3.0 / 2.0f64.sqrt();
        let side = surface_normal(&p, Vec3::new(s, 0.0, 3.0 - s)).expect("has a surface");
        let want = 1.0 / 2.0f64.sqrt();
        assert!(
            (side.x - want).abs() < 1.0e-9 && (side.z + want).abs() < 1.0e-9,
            "45 degrees round a ball nose points out and down, got {side:?}"
        );
    }

    #[test]
    fn a_corner_radius_is_a_torus_and_knows_which_way_is_out() {
        // The one element whose centre sits off the axis. Radius 5, corner 2, so
        // the arc is centred at (3, 2).
        let p = bull_end_mill(10.0, 2.0, 20.0, &Shank::plain(8.0, 40.0)).expect("valid");
        let equator = surface_normal(&p, Vec3::new(5.0, 0.0, 2.0)).expect("has a surface");
        assert!(
            (equator.x - 1.0).abs() < 1.0e-9 && equator.z.abs() < 1.0e-9,
            "the outer equator of the corner torus points +X, got {equator:?}"
        );
        let under = surface_normal(&p, Vec3::new(3.0, 0.0, 0.0)).expect("has a surface");
        assert!(
            under.z < -0.999,
            "under the corner torus is -Z, got {under:?}"
        );

        // Halfway round the corner, at 45 degrees from the centre.
        let s = 2.0 / 2.0f64.sqrt();
        let mid = surface_normal(&p, Vec3::new(3.0 + s, 0.0, 2.0 - s)).expect("has a surface");
        let want = 1.0 / 2.0f64.sqrt();
        assert!(
            (mid.x - want).abs() < 1.0e-9 && (mid.z + want).abs() < 1.0e-9,
            "the corner blends from -Z to +X through (0.707, 0, -0.707), got {mid:?}"
        );
    }

    #[test]
    fn the_normal_agrees_with_a_numerical_gradient() {
        // An independent check on the whole derivation. Containment is a
        // predicate the raycaster and the profile agree on and this module never
        // consults, so probing it either side of the surface tests the algebra
        // against the geometry rather than against itself.
        let profiles = [
            flat_end_mill(6.0, 20.0, &Shank::plain(6.0, 40.0)).expect("valid"),
            ball_end_mill(6.0, 20.0, &Shank::plain(6.0, 40.0)).expect("valid"),
            bull_end_mill(10.0, 2.0, 20.0, &Shank::plain(8.0, 40.0)).expect("valid"),
        ];
        let step = 1.0e-4;
        let mut checked = 0usize;
        for profile in &profiles {
            for element in profile.elements() {
                for i in 1..8 {
                    let u = f64::from(i) / 8.0;
                    let rz = element.element.point_at(u);
                    for bearing in 0..4 {
                        let a = f64::from(bearing) * core::f64::consts::PI / 2.0 + 0.3;
                        let (sin, cos) = t::sin_cos(a);
                        let p = Vec3::new(rz.x * cos, rz.x * sin, rz.y);
                        let n = surface_normal(profile, p).expect("has a surface");

                        let out = p + n * step;
                        let inn = p - n * step;
                        assert!(
                            !profile.contains_xyz(out),
                            "stepping along the normal from {p:?} stayed inside"
                        );
                        assert!(
                            profile.contains_xyz(inn),
                            "stepping against the normal from {p:?} left the solid"
                        );
                        checked += 1;
                    }
                }
            }
        }
        assert!(checked >= 100, "too few probes: {checked}");
    }

    #[test]
    fn every_normal_is_a_unit_vector() {
        let p = bull_end_mill(10.0, 2.0, 20.0, &Shank::plain(8.0, 40.0)).expect("valid");
        for z in [0.0, 0.5, 1.0, 2.0, 5.0, 12.0, 19.0, 39.0] {
            for bearing in 0..8 {
                let a = f64::from(bearing) * core::f64::consts::PI / 4.0;
                let (sin, cos) = t::sin_cos(a);
                for r in [0.0, 0.7, 3.0, 5.0] {
                    let n =
                        surface_normal(&p, Vec3::new(r * cos, r * sin, z)).expect("has a surface");
                    let len = t::hypot(t::hypot(n.x, n.y), n.z);
                    assert!(
                        (len - 1.0).abs() < 1.0e-12,
                        "normal at r={r} z={z} is not unit: {len}"
                    );
                }
            }
        }
    }
}
