# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Langtfelt

"""Material-removal simulation and machining verification.

The engine computes what a program will leave behind and compares it against
the part you meant to make. It reports findings with the error budget that
makes them evidence rather than assertion, and it declines jobs it cannot
answer for -- by name, with a reason.

    >>> import chipbreaker
    >>> report = chipbreaker.verify(
    ...     program="part.nc", tools="library.json", stock="stock.stl",
    ...     nominal="part.stl",
    ... )
    >>> report["verdict"]["pass"]
    False
    >>> report["verdict"]["gates"]["gouge"]
    {'state': 'fail', 'why': '2 gouges above tolerance'}

A declined job raises `Refused`, and the message is the engine's own sentence:

    >>> try:
    ...     chipbreaker.verify(program="siemens.mpf", tools=..., stock=...)
    ... except chipbreaker.Refused as e:
    ...     print(e)
    line 5: this looks like Siemens 840D, which is a different language rather
    than a dialect of RS-274 (found "DEF REAL")

**A refusal is an answer, not a failure.** Show the message and stop. Retrying
will produce the same one, because nothing about the input has changed.

**An unchecked gate does not pass.** Running without a nominal does not give
you a clean part; it gives you a report saying the gouge gate never ran.
`report["verdict"]["pass"]` is False, correctly, and the gate says why.
"""

from __future__ import annotations

import os
from typing import Any, Dict, Optional, Union

from ._chipbreaker import (
    Refused,
    engine_version,
    run,
    selftest_case_count,
    selftest_digest,
    selftest_passed,
)

__all__ = [
    "Refused",
    "engine_version",
    "run",
    "selftest_case_count",
    "selftest_digest",
    "selftest_passed",
    "verify",
]

__version__ = engine_version()

PathOrBytes = Union[str, bytes, "os.PathLike[str]"]


def _as_bytes(value: PathOrBytes, what: str) -> bytes:
    """Accepts a path or the bytes themselves.

    A caller who already has the mesh in memory -- out of a database, off a
    socket, generated by their own CAD kernel -- should not have to write it to
    a temporary file to hand it over. A caller who has a path should not have to
    open it. Both are common, and distinguishing them costs one isinstance.
    """
    if isinstance(value, bytes):
        return value
    try:
        with open(value, "rb") as handle:
            return handle.read()
    except OSError as exc:
        raise OSError(f"could not read the {what}: {exc}") from exc


def _as_text(value: PathOrBytes, what: str) -> str:
    """Reads text **in binary and decodes**, never in text mode.

    Text mode performs universal-newline translation, so on Windows a file
    containing CRLF is delivered to the engine with LF -- different bytes, and
    therefore a different content digest in the manifest. The same program file
    verified through Python and through the C ABI produced two different
    manifest identities, which is precisely the drift the shared assembly
    exists to prevent, arriving through the wrapper instead.

    The engine's lexer handles CR itself. What it must not receive is bytes
    that differ from the ones on disk.
    """
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    try:
        with open(value, "rb") as handle:
            return handle.read().decode("utf-8", errors="replace")
    except OSError as exc:
        raise OSError(f"could not read the {what}: {exc}") from exc


def verify(
    *,
    program: PathOrBytes,
    tools: PathOrBytes,
    stock: PathOrBytes,
    nominal: Optional[PathOrBytes] = None,
    tool: Optional[str] = None,
    resolution_mm: float = 0.5,
    tolerance_mm: float = 0.1,
    clearance_mm: float = 0.0,
    memory_ceiling_bytes: Optional[int] = None,
) -> Dict[str, Any]:
    """Verifies one program against one stock, and optionally one nominal part.

    Every argument is keyword-only. Four of them are meshes or text that look
    alike at a call site, and a positional API would let two of them be
    transposed silently -- a mistake that produces a plausible wrong answer
    rather than an error.

    :param program: the NC program, as a path or as bytes
    :param tools: the tool library JSON, as a path or as bytes
    :param stock: the stock mesh, STL, binary or ASCII
    :param nominal: the finished part. **Omitting it does not mean the part is
        good**; it means the gouge gate reports `unchecked` and the verdict does
        not pass.
    :param tool: which tool from the library. Defaults to the program's first
        ``T`` word.
    :param resolution_mm: dexel spacing. Smaller is more accurate and costs
        memory as the square.
    :param tolerance_mm: what counts as a defect.
    :param clearance_mm: below this, a pass near an obstacle is reported as a
        near miss. Near misses do not fail the collision gate.
    :param memory_ceiling_bytes: refuse rather than allocate beyond this. Worth
        setting in any long-lived process: exceeding it produces a sentence
        naming a resolution that would fit, instead of an allocation failure.

    :returns: the report, as a dict. See ``docs/report-schema.md``.
    :raises Refused: the engine declined. ``str(exc)`` is why.
    :raises OSError: an input could not be read.
    """
    return run(
        _as_text(program, "program"),
        _as_text(tools, "tool library"),
        _as_bytes(stock, "stock mesh"),
        nominal_stl=None if nominal is None else _as_bytes(nominal, "nominal mesh"),
        tool=tool,
        source=str(program) if not isinstance(program, bytes) else "(bytes)",
        resolution_mm=resolution_mm,
        tolerance_mm=tolerance_mm,
        clearance_mm=clearance_mm,
        memory_ceiling_bytes=memory_ceiling_bytes,
    )
