// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Langtfelt

//! The versioned tool corpus, checked against independently computed answers.
//!
//! # Why the expectations are not generated by this crate
//!
//! `tests/corpus/tool/standard-library.json` is a fixture and is generated from
//! the catalogue — it is the *input*, so producing it with the code under test
//! is fine. `expectations.json` is not: it holds the answers, and answers
//! produced by the code under test would establish only that the code agrees
//! with itself. They are computed by `scripts/tool_corpus_expectations.py` from
//! textbook formulas — `pi r^2 h` for a cylinder, `pi h (R^2 + Rr + r^2) / 3`
//! for a frustum, Pappus for a torus band — and each is cross-checked there
//! against numerical quadrature to 1e-9.
//!
//! So a failure here means Chipbreaker disagrees with the textbook, which is the
//! only kind of disagreement worth being told about.

use std::collections::BTreeMap;
use std::path::PathBuf;

use chipbreaker_core::math::{Ray, Vec3};
use chipbreaker_core::mesh::validate::validate;
use chipbreaker_core::tool::io::ToolLibrary;
use chipbreaker_core::tool::{ElementRole, Tool};
use serde_json::Value;

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("tests/corpus/tool")
}

fn library() -> ToolLibrary {
    let path = corpus_dir().join("standard-library.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    ToolLibrary::from_json(&text)
        .unwrap_or_else(|e| panic!("{} is not a valid tool library: {e}", path.display()))
}

fn expectations() -> BTreeMap<String, Value> {
    let path = corpus_dir().join("expectations.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let doc: Value = serde_json::from_str(&text).expect("expectations are JSON");
    assert_eq!(
        doc["schema"], "chipbreaker.tool-corpus-expectations",
        "the expectations file is not what it claims to be"
    );
    doc["tools"]
        .as_object()
        .expect("a tools object")
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect()
}

/// Relative agreement, since a volume spans orders of magnitude between a V-bit
/// tip and a holder.
fn close(actual: f64, expected: f64, tolerance: f64) -> bool {
    (actual - expected).abs() <= tolerance * actual.abs().max(expected.abs()).max(1.0)
}

#[test]
fn the_corpus_library_loads_and_covers_every_expectation() {
    let library = library();
    let expected = expectations();

    assert!(!library.is_empty(), "the corpus library is empty");
    assert_eq!(
        library.len(),
        expected.len(),
        "the library holds {} tools and the expectations name {}; \
         one of the two files was regenerated without the other",
        library.len(),
        expected.len()
    );
    for name in expected.keys() {
        assert!(
            library.get(name).is_some(),
            "the expectations name `{name}`, which the library does not hold"
        );
    }
}

#[test]
fn every_tool_matches_its_independently_computed_properties() {
    let library = library();
    for (name, want) in expectations() {
        let tool: &Tool = library.get(&name).expect("checked above");
        let profile = tool.profile();

        let volume = want["volume"].as_f64().expect("a volume");
        assert!(
            close(profile.volume(), volume, 1e-12),
            "{name}: volume {} against an independently computed {volume} ({})",
            profile.volume(),
            want["formula"].as_str().unwrap_or("")
        );

        if let Some(area) = want["area"].as_f64() {
            assert!(
                close(profile.surface_area(), area, 1e-12),
                "{name}: area {} against an independently computed {area}",
                profile.surface_area()
            );
        }

        let diameter = want["diameter"].as_f64().expect("a diameter");
        assert!(
            close(2.0 * profile.max_radius(), diameter, 1e-12),
            "{name}: diameter {} against {diameter}",
            2.0 * profile.max_radius()
        );

        let length = want["total_length"].as_f64().expect("a length");
        assert!(
            close(profile.total_length(), length, 1e-12),
            "{name}: length {} against {length}",
            profile.total_length()
        );

        let cutting = want["cutting_length"].as_f64().expect("a cutting length");
        let found = profile
            .top_of_role(ElementRole::Cutting)
            .unwrap_or_else(|| panic!("{name} has no cutting geometry"));
        assert!(
            close(found, cutting, 1e-12),
            "{name}: cutting length {found} against {cutting}"
        );
    }
}

#[test]
fn every_tool_in_the_corpus_survives_a_round_trip() {
    let original = library();
    let text = original.to_json();
    let parsed = ToolLibrary::from_json(&text).expect("what we just wrote");
    assert_eq!(original, parsed);
    assert_eq!(
        text,
        parsed.to_json(),
        "the committed corpus must be a fixed point of write-read-write, \
         or its file would churn on every run"
    );
}

#[test]
fn the_committed_corpus_file_is_exactly_what_this_build_writes() {
    // Guards against the fixture and the writer drifting apart: a corpus file
    // the current build would not produce is a corpus file nobody can
    // regenerate without an unexplained diff.
    let path = corpus_dir().join("standard-library.json");
    let on_disk = std::fs::read_to_string(&path).expect("readable");
    let rewritten = library().to_json();
    assert_eq!(
        on_disk,
        rewritten,
        "{} differs from what this build writes; regenerate it with\n  \
         cargo run -p chipbreaker-core --example generate_tool_corpus > {}",
        path.display(),
        path.display()
    );
}

#[test]
fn every_tool_in_the_corpus_casts_and_tessellates_without_leaking() {
    for tool in library().tools() {
        let profile = tool.profile();
        let name = tool.id().as_str();
        let cylinder = profile.bounding_cylinder();
        let radius = cylinder.radius * 1.25 + 1.0;
        let reach = 2.0 * (radius + cylinder.z_max + 2.0) + 2.0;

        for i in 0..24 {
            let u = -radius + 2.0 * radius * (f64::from(i) + 0.5) / 24.0;
            for j in 0..24 {
                let v = cylinder.z_min - 0.5
                    + (cylinder.z_max - cylinder.z_min + 1.0) * (f64::from(j) + 0.5) / 24.0;
                let ray =
                    Ray::new_normalized(Vec3::new(-radius - 1.0, u, v), Vec3::new(1.0, 0.0, 0.0))
                        .expect("unit");
                for span in profile.intersect_ray(&ray).iter() {
                    assert!(
                        span.t0.is_finite() && span.t1.is_finite() && span.t1 <= reach,
                        "{name}: span {span} leaks past {reach}"
                    );
                }
            }
        }

        let (mesh, _) = profile.tessellate(0.02).expect("a valid tolerance");
        let report = validate(&mesh);
        assert!(
            report.is_solid(),
            "{name}: the tessellated mesh is not a closed oriented solid"
        );
        assert!(
            mesh.signed_volume() <= profile.volume() * (1.0 + 1e-9),
            "{name}: the mesh is not inscribed"
        );
    }
}
