// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Chipbreaker Contributors

//! Regenerates `tests/corpus/tridexel/expectations.json`.
//!
//! Same discipline as the single-bundle corpus: goldens are **digests, not
//! files**, with the per-bundle volumes and the deviation figures alongside so a
//! digest change can be attributed rather than merely noticed.
//!
//! Deviation is recorded because it is the unit's assertion metric (ADR 0005).
//! A digest that moves while the deviation holds still is a serialization
//! change; one where the deviation moves too is a change in where the rays are.

#![allow(missing_docs, reason = "an example binary, not API")]

use chipbreaker_core::dexel::deviation::{coverage, measure, sample_mesh_budget};
use chipbreaker_core::dexel::io as dexel_io;
use chipbreaker_core::dexel::tri::{AXES, AxisSet, TriBuildOptions, TriDexelField};
use chipbreaker_core::golden::CanonicalHash;
use chipbreaker_core::math::{Mat4, Vec3};
use chipbreaker_core::mesh::{MeshMeta, TriMesh, shapes};

struct Case {
    id: &'static str,
    note: &'static str,
    mesh: fn() -> TriMesh,
    spacing: f64,
    axes: &'static str,
}

fn octahedron() -> TriMesh {
    let r = 10.0;
    TriMesh::new(
        vec![
            Vec3::new(r, 0.0, 0.0),
            Vec3::new(-r, 0.0, 0.0),
            Vec3::new(0.0, r, 0.0),
            Vec3::new(0.0, -r, 0.0),
            Vec3::new(0.0, 0.0, r),
            Vec3::new(0.0, 0.0, -r),
        ],
        vec![
            [0, 2, 4],
            [2, 1, 4],
            [1, 3, 4],
            [3, 0, 4],
            [2, 0, 5],
            [1, 2, 5],
            [3, 1, 5],
            [0, 3, 5],
        ],
        MeshMeta::synthetic(),
    )
    .expect("valid")
}

fn cases() -> Vec<Case> {
    vec![
        Case {
            id: "box-non-dividing-spacing",
            note: "1.6 mm divides none of 30, 20, 10: the case that used to abort before \
                   the lattice was centred at U6",
            mesh: || shapes::box_solid(Vec3::new(0.0, 0.0, 0.0), Vec3::new(30.0, 20.0, 10.0)),
            spacing: 1.6,
            axes: "xyz",
        },
        Case {
            id: "octahedron-body-diagonal-faces",
            note: "every face normal is a body diagonal, so the 1/sqrt(3) bound is \
                   ATTAINED rather than merely satisfied",
            mesh: octahedron,
            spacing: 0.5,
            axes: "xyz",
        },
        Case {
            id: "sphere",
            note: "all three bundles symmetric: they must agree exactly",
            mesh: || shapes::icosphere(12.0, 4),
            spacing: 0.4,
            axes: "xyz",
        },
        Case {
            id: "cylinder-upright",
            note: "the anisotropy: the Z bundle samples only the caps, so its deviation \
                   is stuck near half the height at every cell size",
            mesh: || shapes::cylinder(8.0, 24.0, 128),
            spacing: 0.5,
            axes: "xyz",
        },
        Case {
            id: "torus",
            note: "a transverse hole, so rays carry two spans",
            mesh: || shapes::torus(15.0, 4.0, 96, 48),
            spacing: 0.5,
            axes: "xyz",
        },
        Case {
            id: "lattice-block-integer-vertices",
            note: "every vertex an integer: the mesh that would trigger coplanar \
                   rejections if the offset were ever removed, on any axis",
            mesh: || shapes::lattice_block(5),
            spacing: 0.5,
            axes: "xyz",
        },
        Case {
            id: "sphere-two-bundles-only",
            note: "xz only: no 1/sqrt(3) guarantee, and must not hash like the \
                   three-bundle field",
            mesh: || shapes::icosphere(12.0, 4),
            spacing: 0.4,
            axes: "xz",
        },
    ]
}

fn main() {
    println!("{{");
    println!("  \"_note\": \"Generated by examples/generate_tri_corpus.rs. Do not hand-edit.\",");
    println!(
        "  \"_metric\": \"Deviation is the assertion metric (ADR 0005). Volume is recorded \
         per bundle as a diagnostic only; the bundles are NOT expected to agree.\","
    );
    println!("  \"cases\": [");

    let all = cases();
    for (index, case) in all.iter().enumerate() {
        let mesh = (case.mesh)();
        let axes = AxisSet::parse(case.axes).expect("valid axes");
        let (field, stats) = TriDexelField::build(
            &mesh,
            &TriBuildOptions {
                spacing: case.spacing,
                axes,
                placement: Mat4::IDENTITY,
                margin: 0.0,
            },
        )
        .unwrap_or_else(|e| panic!("{}: {e}", case.id));

        let mut h = CanonicalHash::new();
        h.add(&field);
        let digest = h.finish().to_hex();

        let bytes = dexel_io::tri_to_bytes(&field).expect("writes");
        let mut bh = CanonicalHash::new();
        bh.bytes(&bytes);
        let file_digest = bh.finish().to_hex();

        let (samples, _) = sample_mesh_budget(&mesh, 4_000);
        let report = measure(&field, &samples);
        let (cover, _) = coverage(&mesh, axes);

        let volumes: Vec<String> = AXES
            .iter()
            .map(|a| {
                field
                    .bundle(*a)
                    .map_or_else(|| "null".to_owned(), |b| format!("{:.17e}", b.volume()))
            })
            .collect();

        println!("    {{");
        println!("      \"id\": \"{}\",", case.id);
        println!("      \"note\": \"{}\",", case.note);
        println!("      \"axes\": \"{}\",", case.axes);
        println!("      \"spacing_mm\": {},", case.spacing);
        println!("      \"rays\": {},", stats.rays);
        println!("      \"spans\": {},", stats.spans);
        println!("      \"coplanar_rejected\": {},", stats.coplanar_rejected);
        println!("      \"bytes\": {},", field.bytes());
        println!("      \"volumes_mm3\": [{}],", volumes.join(", "));
        println!("      \"deviation_best_max_mm\": {:.17e},", report.best_max);
        println!("      \"deviation_constant\": {:.17e},", report.constant());
        println!("      \"worst_cosine\": {cover:.17e},");
        println!("      \"file_bytes\": {},", bytes.len());
        println!("      \"file_digest\": \"{file_digest}\",");
        println!("      \"digest\": \"{digest}\"");
        print!("    }}");
        println!("{}", if index + 1 == all.len() { "" } else { "," });
    }
    println!("  ]");
    println!("}}");
}
