// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Chipbreaker Contributors

//! End-to-end tests for `chipbreaker mesh`, plus the corpus generator.
//!
//! The corpus is generated by an `#[ignore]`d test rather than a separate
//! binary: the generator makes the files reproducible, and the files being
//! committed makes the tests fast and independent of generator changes. Run it
//! deliberately with
//! `cargo test -p chipbreaker-cli --test corpus -- --ignored regenerate`.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

fn binary() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_chipbreaker"))
}

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/corpus/mesh")
}

fn run(args: &[&str]) -> (i32, String, String) {
    let output = Command::new(binary())
        .args(args)
        .output()
        .expect("the chipbreaker binary must be runnable");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).into_owned(),
        String::from_utf8_lossy(&output.stderr).into_owned(),
    )
}

fn corpus_file(name: &str) -> String {
    corpus_dir()
        .join(name)
        .to_str()
        .expect("utf-8 path")
        .to_owned()
}

/// The well-formed corpus solids. The corpus itself, and the expectations for
/// every entry including the broken ones, live in `corpus.rs`.
const GOOD_MESHES: [&str; 17] = [
    "cube-coarse",
    "box-oblong",
    "sphere-0",
    "sphere-1",
    "sphere-2",
    "cylinder-8",
    "cylinder-32",
    "cylinder-128",
    "cone-8",
    "cone-32",
    "cone-128",
    "torus-16",
    "torus-32",
    "torus-64",
    "lattice-1",
    "lattice-3",
    "lattice-5",
];

#[test]
fn units_are_required_and_unknown_ones_are_rejected() {
    // The single most important CLI behaviour in this unit: refusing to guess.
    let file = corpus_file("cube-coarse.stl");
    let (code, _, stderr) = run(&["mesh", "inspect", &file]);
    assert_ne!(code, 0, "--units must be required");
    assert!(stderr.contains("units"), "{stderr}");

    let (code, _, stderr) = run(&["mesh", "inspect", &file, "--units", "furlongs"]);
    assert_ne!(code, 0);
    assert!(
        stderr.contains("carry no unit information") || stderr.contains("furlongs"),
        "the error must explain why a unit is needed: {stderr}"
    );
}

#[test]
fn inspect_reports_geometry_and_welding() {
    let file = corpus_file("cube-coarse.stl");
    let (code, stdout, _) = run(&["mesh", "inspect", &file, "--units", "mm", "--json"]);
    assert_eq!(code, 0, "{stdout}");
    let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
    let r = &v["results"];
    assert_eq!(r["triangles"], Value::from(12));
    // An STL soup of 12 triangles welds back to a cube's 8 corners.
    assert_eq!(r["load"]["vertices_before_weld"], Value::from(36));
    assert_eq!(r["load"]["vertices_after_weld"], Value::from(8));
    assert_eq!(r["load"]["format"], Value::from("stl-binary"));
    assert!((r["signed_volume_mm3"].as_f64().expect("number") - 1000.0).abs() < 1e-9);
    assert!(r["hash"].is_string());
    assert!(v["environment"]["elapsed_ms"].is_number());
}

#[test]
fn the_same_file_read_as_inches_is_bigger() {
    let file = corpus_file("cube-coarse.stl");
    let mm: Value =
        serde_json::from_str(&run(&["mesh", "inspect", &file, "--units", "mm", "--json"]).1)
            .expect("valid JSON");
    let inch: Value =
        serde_json::from_str(&run(&["mesh", "inspect", &file, "--units", "in", "--json"]).1)
            .expect("valid JSON");
    let a = mm["results"]["signed_volume_mm3"].as_f64().expect("number");
    let b = inch["results"]["signed_volume_mm3"]
        .as_f64()
        .expect("number");
    assert!((b / a - 25.4f64.powi(3)).abs() < 1e-6, "{a} vs {b}");
    // And the hashes differ, because the geometry genuinely differs.
    assert_ne!(mm["results"]["hash"], inch["results"]["hash"]);
}

#[test]
fn validate_reports_every_corpus_solid_as_solid() {
    for name in GOOD_MESHES {
        let file = corpus_file(&format!("{name}.stl"));
        let (code, stdout, stderr) = run(&["mesh", "validate", &file, "--units", "mm", "--json"]);
        assert_eq!(code, 0, "{name}: {stdout}{stderr}");
        let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
        let report = &v["results"]["report"];
        assert_eq!(report["is_solid"], Value::Bool(true), "{name}");
        assert_eq!(report["is_watertight"], Value::Bool(true), "{name}");
        assert_eq!(report["is_manifold"], Value::Bool(true), "{name}");
        assert_eq!(
            report["findings"].as_array().expect("array").len(),
            0,
            "{name} has findings: {}",
            report["findings"]
        );
    }
}

#[test]
fn the_torus_is_reported_as_genus_one() {
    let file = corpus_file("torus-32.stl");
    let (code, stdout, _) = run(&["mesh", "validate", &file, "--units", "mm", "--json"]);
    assert_eq!(code, 0);
    let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
    let component = &v["results"]["report"]["components"][0];
    assert_eq!(component["genus"], Value::from(1));
    assert_eq!(component["euler_characteristic"], Value::from(0));
}

#[test]
fn parity_finds_no_leaks_on_the_adversarial_lattice() {
    // The Unit 5 contract, from the command line.
    for name in ["lattice-3", "lattice-5"] {
        let file = corpus_file(&format!("{name}.stl"));
        let (code, stdout, stderr) = run(&[
            "mesh",
            "parity",
            &file,
            "--units",
            "mm",
            "--lattice",
            "48",
            "--align-to-vertices",
            "--json",
        ]);
        assert_eq!(code, 0, "{name}: {stdout}{stderr}");
        let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
        let r = &v["results"];
        assert_eq!(r["leaks"], Value::from(0), "{name} leaked: {r}");
        assert_eq!(r["rays_cast"], Value::from(48 * 48));
        assert!(
            r["sos_resolutions"].as_u64().expect("number") > 0,
            "{name}: aligned rays must hit degenerate configurations"
        );
    }
}

#[test]
fn bvh_topology_hash_is_stable_across_runs() {
    let file = corpus_file("sphere-2.stl");
    let first: Value =
        serde_json::from_str(&run(&["mesh", "bvh", &file, "--units", "mm", "--json"]).1)
            .expect("valid JSON");
    let second: Value =
        serde_json::from_str(&run(&["mesh", "bvh", &file, "--units", "mm", "--stats", "--json"]).1)
            .expect("valid JSON");
    assert_eq!(
        first["results"]["topology_hash"],
        second["results"]["topology_hash"]
    );
    assert!(first["results"]["nodes"].as_u64().expect("number") > 1);
    assert!(first["results"]["max_depth"].as_u64().expect("number") > 1);
}

#[test]
fn raycast_reports_two_crossings_through_a_cube() {
    let file = corpus_file("cube-coarse.stl");
    let (code, stdout, _) = run(&[
        "mesh", "raycast", &file, "--units", "mm", "--origin", "5,5,-10", "--dir", "0,0,1",
        "--all", "--json",
    ]);
    assert_eq!(code, 0, "{stdout}");
    let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
    let crossings = v["results"]["crossings"].as_array().expect("array");
    assert_eq!(crossings.len(), 2);
    assert_eq!(crossings[0]["entering"], Value::Bool(true));
    assert_eq!(crossings[1]["entering"], Value::Bool(false));
    assert!((crossings[0]["t"].as_f64().expect("number") - 10.0).abs() < 1e-9);
}

#[test]
fn convert_round_trips_through_every_format() {
    let dir = std::env::temp_dir().join(format!("chipbreaker-convert-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("temp dir");
    let source = corpus_file("sphere-1.stl");

    for (extension, format) in [("stl", "stl-binary"), ("stla", "stl-ascii"), ("obj", "obj")] {
        let out = dir.join(format!("out.{extension}"));
        let out_str = out.to_str().expect("utf-8");
        let (code, stdout, stderr) = run(&[
            "mesh", "convert", &source, out_str, "--units", "mm", "--json",
        ]);
        assert_eq!(code, 0, "{extension}: {stdout}{stderr}");
        let v: Value = serde_json::from_str(&stdout).expect("valid JSON");
        assert_eq!(v["results"]["output_format"], Value::from(format));

        // The converted file must load back to the same geometry.
        let (code, back, _) = run(&["mesh", "inspect", out_str, "--units", "mm", "--json"]);
        assert_eq!(code, 0, "reloading {extension}");
        let back: Value = serde_json::from_str(&back).expect("valid JSON");
        let original: Value =
            serde_json::from_str(&run(&["mesh", "inspect", &source, "--units", "mm", "--json"]).1)
                .expect("valid JSON");
        assert_eq!(
            back["results"]["triangles"], original["results"]["triangles"],
            "{extension} changed the triangle count"
        );
        let a = back["results"]["signed_volume_mm3"]
            .as_f64()
            .expect("number");
        let b = original["results"]["signed_volume_mm3"]
            .as_f64()
            .expect("number");
        assert!((a - b).abs() < 1e-6, "{extension}: {a} vs {b}");
    }

    // An unsupported extension is a clean error rather than a silent no-op.
    let bad = dir.join("out.ply");
    let (code, _, stderr) = run(&[
        "mesh",
        "convert",
        &source,
        bad.to_str().expect("utf-8"),
        "--units",
        "mm",
    ]);
    assert_ne!(code, 0);
    assert!(stderr.contains("supported output extensions"), "{stderr}");

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn a_missing_file_is_a_clean_error() {
    let (code, _, stderr) = run(&["mesh", "inspect", "no-such-file.stl", "--units", "mm"]);
    assert_eq!(code, 1);
    assert!(stderr.contains("cannot read"), "{stderr}");
}
